# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20171025_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_course',
            field=models.ManyToManyField(related_name='teach', to='info.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='student_course',
            field=models.ManyToManyField(related_name='stu', to='info.Course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
