# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20171025_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_course',
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
