# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20171025_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Course'),
        ),
    ]
