# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_teacher_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Course'),
        ),
    ]
