# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
